In [16]:
import numpy as np

arr = np.random.choice(np.arange(1, 21), size=15, replace=False)
print(arr)

arr = arr.reshape(3,5)
print(arr)

print(arr.shape)

vals = np.argmax(arr, axis=1)
arr[np.arange(arr.shape[0]), vals] = 0
print(arr)

[ 4 11 12 19 14  2 18  7 13 20  3  9  5 16 15]
[[ 4 11 12 19 14]
 [ 2 18  7 13 20]
 [ 3  9  5 16 15]]
(3, 5)
[[ 4 11 12  0 14]
 [ 2 18  7 13  0]
 [ 3  9  5  0 15]]


In [17]:
brr = np.random.randint(0, 100, size=(4, 3), dtype=np.int32)
print(brr)

print(brr.shape)

print(type(brr))

print(brr.dtype)

[[27 49 18]
 [21 63  4]
 [17 25 49]
 [54 91 86]]
(4, 3)
<class 'numpy.ndarray'>
int32


In [18]:
crr = np.array([[3, -2],[1, 0]])

values, vectors = np.linalg.eig(crr)

print(values)
print(vectors)

[2. 1.]
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [19]:
drr = np.array([[0, 1, 2],
                [3, 4, 5]])

diag = np.trace(drr)

print(diag)

4


In [20]:
err = np.arange(1,7)
print(err)

err = err.reshape(3,2)
print(err)

err = err.reshape(2,3)
print(err)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
